apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matrix
  template:
    metadata:
      labels:
        app: matrix
    spec:
      containers:
        - name: matrix
          image: chatbot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: matrix-pvc
